name: ecommerce_app
description: A simple e-commerce app built with Flutter.

environment:
  sdk: ">=3.5.0 <4.0.0"  # Add this line to specify the SDK version

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # Ensure you have the http package added
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: ^3.2.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0

flutter:
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter